name: Scheduled
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  main-snap:
    uses: ubuntu-robotics/snap_configuration/.github/workflows/snap.yaml@main
  howto-pull-configuration-snap:
    uses: ubuntu-robotics/snap_configuration/.github/workflows/snap.yaml@ci/pull_configuration_from_a_server
