name: snap
on:
  push:
    branches:
      - howto/overwritable_configuration
  pull_request:
    branches:
      - howto/overwritable_configuration
  workflow_dispatch:
  workflow_call:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/build-install-test-snap.yaml@main
    with:
      git-ref: howto/overwritable_configuration
