name: snap
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
       branch-name:
         required: false
         type: string
         default: ''

jobs:
  main-snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    with:
      git-ref: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
