name: snap
on:
  push:
    branches:
      - howto/pull_configuration_from_a_server
  pull_request:
    branches:
      - howto/pull_configuration_from_a_server
  workflow_call:
    inputs:
       branch-name:
         required: false
         type: string
         default: ''

jobs:
  snap:
    uses: ubuntu-robotics/snap_workflows/.github/workflows/snap.yaml@main
    with:
      branch-name: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
      snap-name: my-ros2-teleop-test
