name: snap
on:
  push:
    branches:
      - how-to/content_sharing_configuration_snap
  pull_request:
    branches:
      - how-to/content_sharing_configuration_snap
  workflow_dispatch:
  workflow_call:
    inputs:
       branch-name:
         required: false
         type: string
         default: ''

jobs:

  # Collect all relative paths containing a 'snap/snapcraft.yaml'
  collect_snap_names:
    runs-on: ubuntu-latest
    outputs:
      snap-names: ${{ steps.snap-names.outputs.snap-names }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
      - id: snap-names
        run: echo "snap-names=$(find . -type f -name 'snapcraft.yaml' | sed -r 's|^\./([^/]+)/snap/snapcraft.yaml|\1|' | sort | uniq | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  snaps:
    needs: [collect_snap_names]
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    with:
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "medium", "noble"]]'
      snapcraft-source-subdir: "${{ needs.collect_snap_names.outputs.snap-names }}"
      git-ref: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
      snap-test-script: |
        #!/bin/bash

        set -euxo pipefail

        sudo snap connect my-ros2-teleop-test:configuration my-configuration-snap:configuration

        #TODO add a more relevant test
        snap info my-ros2-teleop-test
        snap info my-configuration-snap
