name: snap
on:
  push:
    branches:
      - howto/pull_configuration_from_a_server
  pull_request:
    branches:
      - howto/pull_configuration_from_a_server
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: howto/pull_configuration_from_a_server
    - uses: snapcore/action-build@v1
      id: build-snap

    # Make sure the snap is installable
    - run: |
        sudo snap install ${{ steps.build-snap.outputs.snap }} --dangerous
    # Do some testing with the snap
    - run: |
        snap info my-ros2-teleop-test
    - uses: actions/upload-artifact@v3
      with:
        name: my-ros2-teleop-test
        path: ${{ steps.build-snap.outputs.snap }}
